[profile.default]
src = "pocs"
out = "out"
libs = ["lib"]
test = "pocs"
remappings = ["forge-std/=lib/forge-std/src/"]

[fmt]
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "attributes_first"
single_line_statement_blocks = "preserve"


[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
## Note: You need your own RPC URL. Get a free one from Alchemy, Infura, or QuickNode.


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
